about/urls.py
from django.conf.urls import url
from django.contrib import admin
from about.views import About


app_name='about'

urlpatterns = [
    url(r'^$', About , name='about1'),


]

contact/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import contact


app_name='contact'
urlpatterns = [
    url(r'^$', contact, name='contact1'),


]

donate/urls.py
from django.conf.urls import url
from django.contrib import admin
from donate.views import Donate


app_name='donate'

urlpatterns = [
    url(r'^$', Donate , name='donate1'),


]

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import Post_List, Post_Detail


app_name='myblog'
urlpatterns = [
    url(r'^$', Post_List, name='list'),
    url(r'^(?P<id>\d+)/$', Post_Detail, name='detail'),

]

myproject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from home.views import Post_List, Post_Detail


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls'), ),
    url(r'^about/', include('about.urls'),  ),
    url(r'^quote/', include('quote.urls'),  ),
    url(r'^contact/', include('contact.urls'),  ),
    url(r'^donate/', include('donate.urls'),  ),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quote/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import mar


app_name='quote'
urlpatterns = [
   url(r'^$', mar, name='quotes'), 

]

about/models.py
from django.db import models

class AboutUs(models.Model):
    title = models.CharField(max_length=200, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = "-updated",
        verbose_name_plural = 'About us'

    def __str__(self):
        return self.title

donate/models.py
from django.db import models

class Payment(models.Model):

	title = models.CharField(max_length=200, blank=True)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.title

home/models.py
from django.db import models

from django.core.urlresolvers import reverse


def upload_location(instance, filename):
    return '%s/%s' % (instance.id, filename)


class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=upload_location, null=True,
                              blank=True, height_field='height_field', width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    author = models.CharField(max_length=200)
    body = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url():
        return reverse('myblog:detail', kwargs={'id': self.id})

quote/models.py
from django.db import models

class marq(models.Model):
    text = models.TextField()
    
    def __str__(self):
        return self.text

runserver/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class contactform(forms.Form):
	name = forms.CharField( required=False, max_length=100, help_text='100 characters max')
	email = forms.EmailField(required=True)
	comment=forms.CharField(required=True, widget=forms.Textarea)

about/views.py
from django.shortcuts import render
from .models import AboutUs

def About(request):
    # Get the first about us object
    about_us = AboutUs.objects.first()
    context = {'about_us': about_us}
    return render(request, 'about/about.html', context)

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings 
from .forms import contactform




def contact(request):
	title="Contact"
	form = contactform(request.POST or None)
	confirm_message = None
	if form.is_valid():
		name = form.cleaned_data['name']
		comment = form.cleaned_data['comment']
		subject = 'Message from Mysite.com'
		message = '%s %s ' %(comment, name ) 
		emailFrom = form.cleaned_data['email']
		emailTo = [settings.EMAIL_HOST_USER]
		send_mail(subject, message, emailFrom, emailTo, fail_silently=True )
		title='Thanks'
		confirm_message = "Thanks for the message, we'll get back to you"
		form = None
	context={'title':title,'form':form, 'confirm_message':confirm_message}

	

	return render(request, 'contact/contact.html', context)

donate/views.py
from django.shortcuts import render
from .models import Payment

def Donate(request):
    # Get the first donate object
    donate = Payment.objects.first()
    context = {'donate': donate}
    return render(request, 'donate/donate.html', context)

home/views.py
from django.shortcuts import render

from urllib.parse import quote_plus
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime
from random import randint


def Post_List(request):
    object_list = Post.objects.all().order_by('-published')
# the quotes used in the home page (marquee)
    # all_quote = marq.objects.all()
    # counter = 0
    # for i in all_quote:
    #     counter = counter + 1

    # current_quote = ""
    # first = datetime.date(2017, 10, 6)
    # current = datetime.datetime.now()
    # current_date = datetime.date.isoformat(current)
    # first_date = datetime.date.isoformat(first)

    # if first_date != current_date:
    #     num = randint(1, counter)
    #     current_quote = marq.objects.get(pk=num)
    # else:
    #     first_date = current_date

    paginator = Paginator(object_list, 4)  # 4 posts in each page
    page = request.GET.get('page')
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        object_list = paginator.page(1)
    except EmptyPage:

        # If page is out of range deliver last page of results
        object_list = paginator.page(paginator.num_pages)
    # marquee=Post.objects.marquee()
    context = {'object_list': object_list,
               'page': page}  # 'current_quote': current_quote }
    return render(request, 'home/home.html', context)

#


def Post_Detail(request, id):
    instance = get_object_or_404(Post, id=id)
    share_string = quote_plus(instance.body)
    context = {'instance': instance, 'share_string': share_string}
    return render(request, 'home/detail.html', context)

quote/views.py
from django.shortcuts import render
from .models import marq
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def mar(request):
    inst = marq.objects.all()

    paginator = Paginator(inst, 30)
    page = request.GET.get('page')
    try:
        inst = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        inst = paginator.page(1)
    except EmptyPage:

        # If page is out of range deliver last page of results
        inst = paginator.page(paginator.num_pages)
    # marquee=Post.objects.marquee()
    context = {'inst': inst, 'page': page}
    return render(request, 'quote/quote.html', context)

runserver/views.py
from django.shortcuts import render

# Create your views here.

about/templates/about/about.html
{% extends 'home/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="col-sm-offset-4" >
<img src="{% static 'img/facepic.jpg' %}" class="img-circle img-responsive" alt="Pastor joseph" width="380" >
<h3>Pastor Joseph</h3></br>
<h3>we spread the gospel through out the world daily</h3>
<p>{{ about_us.body|linebreaks|safe }}</p>
</div>

{% endblock content %}

donate/templates/donate/donate.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
<div class="col-sm-offset-4" >
<h3>{{ donate.body|linebreaks|safe }}</h3>
<img src="{% static 'img/gt.jpg' %}" class="" alt="gt-bank logo" width="380" >
<h4> ACCOUNT NAME : ARIMOKWU KILEAMIHIA JOSEPH</h4>
<h4>BANK : GT BANK</h4>
<h4>ACCOUNT NO : 0033616017</h4>

</div>
</div>
{% endblock content %}

home/templates/home/base.html
{% load staticfiles %}
<DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<style>{% block style %} 
.nav > li > a {
  color: black;
  }


  a{color: black;}

.active{background-color: white; }

}

{% endblock %}</style>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<link rel="icon" type="image/jpg" href="/static/img/favicon.jpg">
</head>
<body>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




<nav class="navbar " style="background-color:#058da6 ; color: black;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" >
        <span style='background-color:black;' class="icon-bar"></span>
        <span style='background-color:black;' class="icon-bar"></span>
        <span style='background-color:black;' class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'myblog:list' %}" style='color:black; text-decoration: none;'>FaithEden</a>
    </div>
<div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
{% url 'myblog:list' as home %}
{% url 'about:about1' as about %}
{% url 'quote:quotes' as quotes %}
{% url 'contact:contact1' as contact %}
{% url 'donate:donate1' as donate %}

        <li {% if request.path == home %} style="background-color: #d0d4d6; color:black; " {% endif %} >
        <a href="{% url 'myblog:list' %}" >Home</a></li>
        <li {% if request.path == about %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'about:about1' %}">About Us</a></li>
        <li {% if request.path == quotes %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'quote:quotes' %}">Inspirational Quotes</a></li>
        <li {% if request.path == contact %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'contact:contact1' %}">Contact Us</a></li>
        <li {% if request.path == donate %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'donate:donate1' %}">Donate</a></li>


      </ul>



</div>

</nav>










<div class="container">


<div class="row">

{% block carousel %}
{% endblock %}

</div>



{% block marquee %}
{% endblock %}

{% block follow %}
{% endblock %}

</div>

{% block content %}

{% endblock content %}


<footer >

<div class="col-sm-12" style="background-color:#058da6; color: black;">
<div class="container-fluid">
<div class="row">

 <div class="col-sm-3">


      <h4 style="font-family: 'Satisfy', cursive;" >SITE MAP</h4>
      <ul style="color:black; text-decoration: none;">
        <li ><a style='color:black; text-decoration: none;' href="{% url 'myblog:list' %}" >Home</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'about:about1' %}">About Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'quote:quotes' %}">Inspirational Quotes</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'contact:contact1' %}" >Contact Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'donate:donate1' %}">Donate</a></li>
      </ul>
</div>


<div class="col-sm-3">

    <h4 style="font-family: 'Satisfy', cursive;" >FOLLOW FAITHEDEN ON:</h4>
    <a href="https://www.fb.com/faithlooks">
    <img class="" src="/static/img/fb_logo.jpg" ></a>
    &nbsp&nbsp&nbsp
    <a href="https://www.twitter.com/elanfaith"> <img class="" src="/static/img/twitter_logo.jpg"></a>

</div>

<div class="col-sm-3" >
 <h4 style="font-family: 'Satisfy', cursive;">Design your website<</h4>
 <p style='color:black; text-decoration: none;' >call or whatsapp: 09032841265 , 08182336574</p>
 <p style='color:black; text-decoration: none;'> email : gospeltruth18@gmail.com</p>

</div>



</div>
</div>
</div>

</footer>






<script src="/static/js/jquery-3.2.0.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/main.js"></script>
{% block script %}
 {% endblock %}


</body>
</html>

home/templates/home/rough.html
echo "*.py[cod].DS_Store__pycache__/*.py[cod]*$py.class" > .gitignore

<div class="col-sm-12">
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/static/img/c1.jpg" alt="Chania">
<!--       <div class="carousel-caption">
        <h3>Chania</h3>
        <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
      </div> -->
    </div>

    <div class="item">
      <img src="/static/img/c2.jpg" alt="Chania">
      <div class="carousel-caption">
        <h3>Chania</h3>
        <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
      </div>
    </div>

    <div class="item">
      <img src="/static/img/c3.jpg" alt="Flower">
<!--       <div class="carousel-caption">
        <h3>Flowers</h3>
        <p>Beatiful flowers in Kolymbari, Crete.</p>
      </div> -->
    </div>

    <div class="item">
      <img src="/static/img/g.jpg" alt="Flower">
<!--       <div class="carousel-caption">
        <h3>Flowers</h3>
        <p>Beatiful flowers in Kolymbari, Crete.</p>
      </div> -->
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>





<div class="row">
<div class="col-sm-12">
<div class="container-fluid">
<footer style="background-color:#058da6; color: black;">

  <div class="row">

 <div class="col-sm-3">


      <h4 style="font-family: 'Satisfy', cursive;" >SITE MAP</h4>
      <ul style="color:black; text-decoration: none;">
        <li ><a style='color:black; text-decoration: none;' href="{% url 'myblog:list' %}" >Home</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'about:about1' %}">About Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'quote:quotes' %}">Inspirational Quotes</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'contact:contact1' %}" >Contact Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="{% url 'donate:donate1' %}">Donate</a></li>
      </ul>
</div>

    <div class="col-sm-3">
          <h4 style="font-family: 'Satisfy', cursive;" >FOLLOW FAITHEDEN ON:</h4>
    <a href="https://www.fb.com/faithlooks">
    <img class="" src="/static/img/fb_logo.jpg" ></a>
    &nbsp&nbsp&nbsp
    <a href="https://www.twitter.com/elanfaith"> <img class="" src="/static/img/twitter_logo.jpg"></a>

    </div>
<div class="col-sm-3" >
 <h4 style="font-family: 'Satisfy', cursive;">Design your website<</h4>
 <p style='color:black; text-decoration: none;' >call or whatsapp: 09032841265 , 08182336574</p>
 <p style='color:black; text-decoration: none;'> email : gospeltruth18@gmail.com</p>

</div>
  </div>
</footer>
</div>
</div>
</div>



































{% static 'img/c1.jpg' %}
<div class="jumbotron" style="background-color: #058da6 ;">
    <div class="col-sm-offset-3">
      <h2 style="font-family: 'Satisfy', cursive; color: white;" >FaithEden Daily Devotionals</h2>
    </div>


        <div class="" >
          <h3 style="font-family: 'Satisfy', cursive; color: white;">Inspirational Quote:
            
            <marquee>{{current_quote}}</marquee></h3>
        </div>
          </br></br>
          <div class="jumbo2">
          <div class="col-sm-offset-5">
<a href="www.fb.com/faithlooks">
<img class="" src="/static/img/fb_logo.jpg" ></a>
&nbsp&nbsp&nbsp
<a href="www.twitter.com/elanfaith"> <img class="" src="/static/img/twitter_logo.jpg"></a>

         </div>
         </div>


       
        </div>
</div>



{% load staticfiles %}
<DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="icon" type="image/jpg" href="{% static 'img/favicon' %}">
<style>{% block style %} 
.nav > li > a {
  color: black;
  }


  a{color: black;}

.active{background-color: white; }

}

{% endblock %}</style>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<!-- <link rel="stylesheet" href="{% static 'css/base.css' %}"> -->

</head>
<nav class="navbar navbar-default" style="background-color:#058da6 ; color: black; height:400px;">
        <div class="container">
            <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" >
                  <span style='background-color:black;' class="icon-bar"></span>
                  <span style='background-color:black;' class="icon-bar"></span>
                  <span style='background-color:black;' class="icon-bar"></span>
                </button>
                <span class="navbar-brand" style=''>
                <a href='#' style="text-decoration: none; color:white;  font-family: 'Satisfy', cursive;">FaithEden</a></span>

            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right" style="">
                <li class="active"><a href="#" >Home</a></li>
                <li><a href="#">About us</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Inspirational Quotes</a></li>
                <li><a href="#">Donate</a></li>



            </ul>
            </div>
        </div>

        </br>
        <div style="text-align: center;">
        	{% block jumbo %}
			{% endblock %}
        <a href="www.fb.com/faithlooks" style="text-decoration: none; color: black;">Facebook</a>
         &nbsp&nbsp&nbsp 
         <a href="www.twitter.com/elanfaith" style="text-decoration: none; color: white;">twitter</a></div>
    </nav>



<body>

<div class="container">


{% block marquee %}
{% endblock %}



{% block content %}
{% endblock content %}
</div>




<!-- <footer style="background-color:#058da6;
  color: black;">
<div class="container">
  <div class="row">


    <div class="col-sm-3">
      <h4 style="font-family: 'Satisfy', cursive;" >SITE MAP</h4>
      <ul style="color:black; text-decoration: none;">
        <li ><a style='color:black; text-decoration: none;' h>Home</a></li>
        <li><a style='color:black; text-decoration: none;' href= "#">About Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="#">Inspirational Quotes</a></li>
        <li><a style='color:black; text-decoration: none;' href="#">Contact Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="#">Donate</a></li>
      </ul>
    </div>
    <div class="col-sm-3">
      <h4 style="font-family: 'Satisfy', cursive;" >FOLLOW FAITHEDEN ON:</h4>
<a href="www.fb.com/faithlooks">
<img class="" src="/static/img/fb_logo.jpg" ></a>
&nbsp&nbsp&nbsp
<a href="www.twitter.com/elanfaith"> <img class="" src="/static/img/twitter_logo.jpg"></a>

    </div>
    <div class="col-sm-3" >
 <h4 style="font-family: 'Satisfy', cursive;">Website Designed By</h4>
 <p style='color:black; text-decoration: none;' >09032841265</p>
 <p style='color:black; text-decoration: none;'> email : gospeltruth18@gmail.com</p>
      
    </div>
</div>
  </div>
</footer> -->


<script type='text/javascript' src="https://js.stripe.com/v2/"></script>
<script src="/static/js/jquery-3.2.0.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/main.js"></script>
</body>
</html>






home.html

{% extends 'home/base.html' %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}index{% endblock %} </title>


{% block style %}

div.polaroid {
/*  width: 80%;*/
  background-color: white;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  margin-bottom: 25px;

}


div.container1 {
/*  text-align: center;*/
 <!--  padding: 10px 20px; -->
  width:100%;

} 

{% endblock %}



</head>
<body>
{% block jumbo %}
        <h2 style="font-family: 'Satisfy', cursive; color: white;" >FaithEden Daily Devotionals</h2>
        <h4 style="font-family: 'Satisfy', cursive; color: white;">Inspirational Quote:</h4>
 
{% endblock %}






{% block content %}

<div class="row">
<div class="col-sm-12 col-sm-offset-0.5" ><h3>Latest Posts</h3>
</div>
</div>



{% for obj in object_list %}


<div class="col-sm-3">
  <div class="polaroid" style="height: 500px;">
  <b><h3>{{ obj.title }}</h3><h5>{{ obj.publish }}</h5></b></br>
  <p>{{obj.body|linebreaks|truncatechars:200}}</br></p></br></br>
  <h4>author : {{ obj.author }}</h4>
  <img src="{{obj.image.url}}" alt="ssssshjg" style="width:100%" height="200px">
  <a href="" style="text-decoration: none; color: inherit;">

    <div class="container1" >
      
      
        
        
      </a>
    </div>
  </div>
</div>


{% endfor %}
{% include "home/pagination.html" with page=object_list %}


{% endblock %}
</body>
</html>



































{% load staticfiles %}
<DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<style>{% block style %} 
.nav > li > a {
  color: black;
  }


  a{color: black;}

.active{background-color: white; }

}

{% endblock %}</style>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<link rel="icon" type="image/jpg" href="/static/img/favicon.jpg">
</head>
<body>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




<nav class="navbar " style="background-color:#058da6 ; color: black;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" >
        <span style='background-color:black;' class="icon-bar"></span>
        <span style='background-color:black;' class="icon-bar"></span>
        <span style='background-color:black;' class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'myblog:list' %}" style='color:black; text-decoration: none;'>FaithEden</a>
    </div>
<div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
{% url 'myblog:list' as home %}
{% url 'about:about1' as about %}
{% url 'quote:quotes' as quotes %}
{% url 'contact:contact1' as contact %}
{% url 'donate:donate1' as donate %}

        <li {% if request.path == home %} style="background-color: #d0d4d6; color:black; " {% endif %} >
        <a href="{% url 'myblog:list' %}" >Home</a></li>
        <li {% if request.path == about %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'about:about1' %}">About Us</a></li>
        <li {% if request.path == quotes %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'quote:quotes' %}">Inspirational Quotes</a></li>
        <li {% if request.path == contact %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'contact:contact1' %}">Contact Us</a></li>
        <li {% if request.path == donate %} style="background-color: #d0d4d6; color:black; " {% endif %} ><a href="{% url 'donate:donate1' %}"> Donate</a></li>

      </ul>



</div>

</nav>










<div class="container">


<div class="row">
<div class="col-sm-9 col-sm-offset-2">
{% block jumbo %}
{% endblock %}
</div>
</div>

{% block hr %}
</br></br></br>
{% endblock %}

{% block marquee %}
{% endblock %}

{% block follow %}
{% endblock %}

</div>

{% block content %}

{% endblock content %}






<div class="container-fluid">
<footer style="background-color:#058da6;
  color: black;">

  <div class="row">

 <div class="col-sm-3">


      <h4 style="font-family: 'Satisfy', cursive;" >SITE MAP</h4>
      <ul style="color:black; text-decoration: none;">
        <li ><a style='color:black; text-decoration: none;' href="#">Home</a></li>
        <li><a style='color:black; text-decoration: none;' href= "">About Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="#">Inspirational Quotes</a></li>
        <li><a style='color:black; text-decoration: none;' href="#">Contact Us</a></li>
        <li><a style='color:black; text-decoration: none;' href="#">Donate</a></li>
      </ul>
</div>

<div class="col-sm-3">
      <h4 style="font-family: 'Satisfy', cursive;" >FOLLOW FAITHEDEN ON:</h4>
<a href="www.fb.com/faithlooks">
<img class="" src="/static/img/fb_logo.jpg" ></a>
&nbsp&nbsp&nbsp
<a href="www.twitter.com/elanfaith"> <img class="" src="/static/img/twitter_logo.jpg"></a>

</div>
<div class="col-sm-3" >
 <h4 style="font-family: 'Satisfy', cursive;">Design your website<</h4>
 <p style='color:black; text-decoration: none;' >call or whatsapp: 09032841265 , 08182336574</p>
 <p style='color:black; text-decoration: none;'> email : gospeltruth18@gmail.com</p>

</div>
  </div>
</footer>
</div>




<script src="/static/js/jquery-3.2.0.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/main.js"></script>
{% block script %}
 {% endblock %}


</body>
</html>